### PR TITLE
Refactoring and updating payment

### PR DESCRIPTION
**Pull request by kara-sky**
* Did refactoring
* Updated payment

### CODE REVIEW

**Comment by EllaMcKee3** [comment]
1) Should we add more structure and description to the PR? It would help to explain to the team more clearly what changes were made. We could structure it something like: summary of changes -> reasons for changes -> end goal of changes
2) It might be good to also include a section on how you tested the changes - any linters, test suites, readme updates, etc.
3) There are quite a lot of different files changed in one go - maybe next time, we could make each commit a different kind of change? e.g. first commit: "update payment function", second commit: "refactor by changing imports for each file"

**Review by DavidCLilley — COMMENTED** [review]
The code looks good though there is no information given on why these changes have taken place and no verification that it has passed the unit tests in the PR.

I would recommend going forward that you separate out different changes into separate PR's in this case. One for refactoring and one for updating payment.

**Comment by nikitashinde1** [comment]
@kara-sky 

Would you be able to add few more details to your PR as below:

- Can you provide some steps or instruction on how to run tests locally. It would be helpful for reviewer.
- It would be good if we can have PR check list for both Developer and Reviewer in description. PR template can be usefull.
- Could you please are more detailed description to your PR
- It would be good, if you can add screenshot of test and lint results.

**Comment by codepozro** [comment]
@kara-sky Could you add the PR template please? https://github.com/sky-uk/cec-finops-kb/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Pull request closed without merging**
